/*
 * Copyright (c) 2026 Leyo Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/// @file version.h
/// @brief Contains the leyo version at compile-time.
/// @warning Automatically generated - do not edit.
/// @note Generated by the Makefile and VERSION.mk.

#ifndef VERSION_H
#define VERSION_H
#define LEYO_VERSION "0.12.1"
#endif
